# Generated by Django 3.0.1 on 2019-12-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
                ('casting_time', models.CharField(max_length=20)),
                ('range', models.CharField(max_length=20)),
                ('components', models.CharField(blank=True, max_length=20)),
                ('duration', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=50)),
                ('attack_save', models.CharField(max_length=100)),
                ('damage_effect', models.CharField(max_length=100)),
                ('higher_levels', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
