# Generated by Django 3.0.1 on 2020-02-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('modifier', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(default='character', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('challenge_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_hp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NPCClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('armor_class', models.IntegerField()),
                ('max_hit_points', models.IntegerField()),
                ('speed', models.CharField(max_length=30)),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('saving_throws', models.CharField(blank=True, max_length=255, null=True)),
                ('damage_resistance', models.CharField(blank=True, max_length=255, null=True)),
                ('damage_immunities', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_immunities', models.CharField(blank=True, max_length=255, null=True)),
                ('senses', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('challenge', models.IntegerField(blank=True, null=True)),
                ('legendary_actions', models.TextField(blank=True, null=True)),
                ('cha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cha', to='gos.AbilityScore')),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='con', to='gos.AbilityScore')),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dex', to='gos.AbilityScore')),
                ('features', models.ManyToManyField(blank=True, to='gos.Feature')),
                ('int', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='int', to='gos.AbilityScore')),
                ('str', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='str', to='gos.AbilityScore')),
                ('wis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wis', to='gos.AbilityScore')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
                ('casting_time', models.CharField(max_length=20)),
                ('range', models.CharField(max_length=20)),
                ('components', models.CharField(blank=True, max_length=20)),
                ('duration', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=50)),
                ('attack_save', models.CharField(max_length=100)),
                ('damage_effect', models.CharField(max_length=100)),
                ('higher_levels', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('monster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gos.Monster')),
                ('bio', models.TextField()),
                ('race', models.CharField(max_length=20)),
                ('alignment', models.CharField(choices=[('Lawful Good', 'Lawful Good'), ('Neutral Good', 'Neutral Good'), ('Chaotic Good', 'Chaotic Good'), ('Lawful Neutral', 'Lawful Neutral'), ('Neutral', 'Neutral'), ('Chaotic Neutral', 'Chaotic Neutral'), ('Lawful Evil', 'Lawful Evil'), ('Neutral Evil', 'Neutral Evil'), ('Chaotic Evil', 'Chaotic Evil')], max_length=30)),
                ('personality_traits', models.TextField(blank=True, null=True)),
                ('ideals', models.TextField(blank=True, null=True)),
                ('bonds', models.TextField(blank=True, null=True)),
                ('flaws', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('secrets', models.TextField(blank=True, null=True)),
            ],
            bases=('gos.monster',),
        ),
        migrations.CreateModel(
            name='SpellSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=30)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('used', models.IntegerField(blank=True, null=True)),
                ('monster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell_slots', to='gos.Monster')),
                ('spells', models.ManyToManyField(to='gos.Spell')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('npc_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='gos.NPCClass')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='npc_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gos.NPCClass'),
        ),
        migrations.CreateModel(
            name='FightMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative_order', models.IntegerField(blank=True, null=True)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos.Fight')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos.Monster')),
            ],
        ),
        migrations.AddField(
            model_name='fight',
            name='members',
            field=models.ManyToManyField(through='gos.FightMember', to='gos.Monster'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attack_type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('npc_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='gos.NPCClass')),
            ],
        ),
    ]
