# Generated by Django 3.0.1 on 2019-12-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField()),
                ('max', models.IntegerField()),
                ('used', models.IntegerField()),
                ('spells', models.ManyToManyField(to='gos.Spell')),
            ],
        ),
    ]
