# Generated by Django 3.0.1 on 2020-03-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='members',
        ),
        migrations.AlterField(
            model_name='fightmember',
            name='fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gos.Fight'),
        ),
    ]
