# Generated by Django 3.0.1 on 2019-12-29 04:52

from django.db import migrations, models
import django.db.models.deletion
import gos.models.npc


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0002_spellslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('modifier', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='spell',
            name='higher_levels',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='NPCClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('armor_class', models.IntegerField()),
                ('max_hit_points', models.IntegerField()),
                ('speed', models.CharField(max_length=30)),
                ('saving_throws', models.CharField(blank=True, max_length=255, null=True)),
                ('damage_resistance', models.CharField(blank=True, max_length=255, null=True)),
                ('damage_immunities', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_immunities', models.CharField(blank=True, max_length=255, null=True)),
                ('senses', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('challenge', models.IntegerField(blank=True, null=True)),
                ('cha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cha', to='gos.AbilityScore')),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='con', to='gos.AbilityScore')),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dex', to='gos.AbilityScore')),
                ('features', models.ManyToManyField(blank=True, null=True, to='gos.Feature')),
                ('int', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='int', to='gos.AbilityScore')),
                ('str', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='str', to='gos.AbilityScore')),
                ('wis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wis', to='gos.AbilityScore')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('race', models.CharField(max_length=20)),
                ('alignment', models.CharField(choices=[(gos.models.npc.AlignmentType['LG'], 'Lawful Good'), (gos.models.npc.AlignmentType['NG'], 'Neutral Good'), (gos.models.npc.AlignmentType['CG'], 'Chaotic Good'), (gos.models.npc.AlignmentType['LN'], 'Lawful Neutral'), (gos.models.npc.AlignmentType['NN'], 'Neutral'), (gos.models.npc.AlignmentType['CN'], 'Chaotic Neutral'), (gos.models.npc.AlignmentType['LE'], 'Lawful Evil'), (gos.models.npc.AlignmentType['NE'], 'Neutral Evil'), (gos.models.npc.AlignmentType['CE'], 'Chaotic Evil')], max_length=5)),
                ('personality_traits', models.TextField(blank=True, null=True)),
                ('ideals', models.TextField(blank=True, null=True)),
                ('bonds', models.TextField(blank=True, null=True)),
                ('flaws', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('secrets', models.TextField(blank=True, null=True)),
                ('current_hp', models.IntegerField()),
                ('npc_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gos.NPCClass')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reach', models.CharField(blank=True, max_length=20, null=True)),
                ('attack_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('hit', models.CharField(blank=True, max_length=20, null=True)),
                ('damage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('npc_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gos.NPCClass')),
            ],
        ),
        migrations.AddField(
            model_name='spellslot',
            name='npc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gos.NPC'),
        ),
    ]
