# Generated by Django 3.0.1 on 2019-12-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0003_auto_20191229_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='abilityscore',
            options={'ordering': ['score']},
        ),
        migrations.AlterField(
            model_name='npcclass',
            name='features',
            field=models.ManyToManyField(blank=True, to='gos.Feature'),
        ),
    ]
