# Generated by Django 3.0.1 on 2019-12-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0004_auto_20191230_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(default='character', max_length=30),
        ),
    ]
