# Generated by Django 3.0.1 on 2020-01-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0007_auto_20200111_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcclass',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='spellslot',
            name='npc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell_slots', to='gos.NPC'),
        ),
    ]
