# Generated by Django 3.0.1 on 2020-01-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0008_auto_20200125_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcclass',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
