# Generated by Django 3.0.1 on 2020-01-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0009_npcclass_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcclass',
            name='legendary_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='npcclass',
            name='reactions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='npc_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='gos.NPCClass'),
        ),
    ]
