# Generated by Django 3.0.1 on 2020-01-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0010_auto_20200125_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcclass',
            name='short_description',
            field=models.CharField(default='Medium humanoid (any race), any alignment', max_length=255),
            preserve_default=False,
        ),
    ]
