# Generated by Django 3.0.1 on 2020-01-26 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0011_npcclass_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='attack_bonus',
        ),
        migrations.RemoveField(
            model_name='action',
            name='damage_type',
        ),
        migrations.RemoveField(
            model_name='action',
            name='hit',
        ),
        migrations.RemoveField(
            model_name='action',
            name='reach',
        ),
        migrations.RemoveField(
            model_name='npcclass',
            name='reactions',
        ),
        migrations.AddField(
            model_name='action',
            name='attack_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('npc_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='gos.NPCClass')),
            ],
        ),
    ]
