# Generated by Django 3.0.1 on 2020-02-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0012_auto_20200126_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcclass',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
