# Generated by Django 3.0.1 on 2020-02-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0013_auto_20200219_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcclass',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='npcclass',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
    ]
