# Generated by Django 3.0.1 on 2020-02-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0014_auto_20200219_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellslot',
            name='max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spellslot',
            name='used',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
